spring:
  application:
    name: crawler-dytt
#  data:
#    elasticsearch:
#      cluster-name: elasticsearch_wxl
#      cluster-nodes: localhost:9300
#      repositories:
#        enabled: false
  elasticsearch:
    rest:
      uris: http://localhost:9200

#  redis:
#    host: localhost
#    port: 6379
#    database: 0
#    timeout: 5s
#    lettuce:
#      pool:
#        max-active: 8
#        max-idle: 3
#        min-idle: 1
#        max-wait: 5s
#

logging:
  level:
    root: info
    com.wxl.crawlerdytt: debug

crawler:
  first-url: "https://www.dytt8.net"
  domain: "www.dytt8.net"
  charset: gbk
  pool:
    core-size: 1
    max-size: 1
    keep-alive: 5m
  site:
    sleep-time: 1s
    retry-times: 1
    retry-sleep-time: 1s
    timeout: 10s
    disable-cookie: true
  download:
    ignore-ssl: true
    keep-alive: 3m
    validate-after-inactivity: 1m
  store:
    es:
      retry-timeout: 5s
      request:
        connect-timeout: 5s
        socket-timeout: 10s
        connect-request-timeout: 5s
        compress-enabled: true
      indices:
        dytt-detail:
          index: dytt
          type: _doc
