spring:
  application:
    name: crawler-dytt
  data:
    elasticsearch:
      repositories:
        enabled: false
  elasticsearch:
    rest:
      uris: http://localhost:9200
  redis:
    host: localhost
    port: 6379
    database: 1
    timeout: 5s
    lettuce:
      pool:
        max-active: 8
        max-idle: 4
        min-idle: 1
        max-wait: 5s

logging:
  level:
    root: info
    com.wxl.crawlerdytt: debug

crawler:
  first-url: "https://www.dytt8.net"
  domain: "www.dytt8.net"
  charset: gbk
  max-thread: 1
  site:
    sleep-time: 1s
    retry-times: 2
    retry-sleep-time: 1s
    timeout: 10s
    disable-cookie: true
  download:
    ignore-ssl: true
    keep-alive: 3m
    validate-after-inactivity: 1m
    use-security: false
  scheduler:
    type: redis
  store:
    es:
      retry-timeout: 5s
      request:
        connect-timeout: 5s
        socket-timeout: 10s
        connect-request-timeout: 5s
        compress-enabled: true
      detail:
        index: dytt
        type: _doc

server:
  port: 8080

