spring:
  application:
    name: crawler-dytt
#  redis:
#    host: localhost
#    port: 6379
#    database: 0
#    timeout: 5s
#    lettuce:
#      pool:
#        max-active: 8
#        max-idle: 3
#        min-idle: 1
#        max-wait: 5s
#

logging:
  level:
    root: info
    com.wxl.crawlerdytt: debug
